Add setup file for pip install
bluerobotics/ms5837-python pull request #3
Opened 2017-06-20 21:11 UTC by luciengaitskell

This addition of a `setup.py` file allows for this library to be `pip install`ed, for ease of installation. Additionally, the main library script has been moved into a package directory.

2019-03-14 14:58 UTC, jaxxzer commented
Fix #6

2019-03-18 14:49 UTC, Williangalvani requested changes
Hello @luciengaitskell, 
I'm sorry for the really long time to review it.
Would you mind rebasing it and changing some minor things so we can merge it?

2019-03-18 14:49 UTC, Williangalvani commented on example.py
> +from MS5837 import ms5837
Since we are trying to follow pep8, [the package name should be lowercase](https://www.python.org/dev/peps/pep-0008/#package-and-module-names).

2019-03-18 14:49 UTC, Williangalvani commented on example.py
> +                sensor.pressure(ms5837.UNITS_psi),  # Request psi
Please indent the other arguments too to keep them aligned.

2019-05-19 17:55 UTC, luciengaitskell commented
@Williangalvani Thanks for coming back to it! I just made the edits. Should be all set now

2021-05-11 20:30 UTC, jaxxzer commented
I merged #15 in favor of this one. Took a while to get around to it, huh.

2021-05-11 20:30 UTC, closed without merging

2021-05-14 14:59 UTC, luciengaitskell commented
@jaxxzer Thank you for sorting out the issue!